// tailwind.config.js
const { heroui } = require("@heroui/react");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "./node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    //Border
    "border-bug",
    "border-dark",
    "border-dragon",
    "border-electric",
    "border-fairy",
    "border-fighting",
    "border-fire",
    "border-flying",
    "border-ghost",
    "border-grass",
    "border-ground",
    "border-ice",
    "border-normal",
    "border-poison",
    "border-psychic",
    "border-rock",
    "border-steel",
    "border-water",
    "bg-bug",
    "bg-dark",
    "bg-dragon",
    "bg-electric",
    "bg-fairy",
    "bg-fighting",
    "bg-fire",
    "bg-flying",
    "bg-ghost",
    "bg-grass",
    "bg-ground",
    "bg-ice",
    "bg-normal",
    "bg-poison",
    "bg-psychic",
    "bg-rock",
    "bg-steel",
    "bg-water",
  ],
  theme: {
    extend: {
      colors: {
        bug: "#a6b91a",
        dark: "#705746",
        dragon: "#6f35fc",
        electric: "#f7d02c",
        fairy: "#d685ad",
        fighting: "#c22e28",
        fire: "#ee8130",
        flying: "#a98ff3",
        ghost: "#735797",
        grass: "#7ac74c",
        ground: "#e2bf65",
        ice: "#96d9d6",
        normal: "#a8a77a",
        poison: "#a33ea1",
        psychic: "#f95587",
        rock: "#b6a136",
        steel: "#b7b7ce",
        water: "#6390f0",
      },
    },
  },
  darkMode: "class",
  plugins: [heroui()],
};
