export const typeBackground: Record<string, string> = {
  bug: "/bug.webp",
  dark: "/dark.webp",
  dragon: "/dragon.webp",
  electric: "/electric.webp",
  fairy: "/fairy.webp",
  fighting: "/fighting.webp",
  fire: "/fire.webp",
  flying: "/flying.webp",
  ghost: "/ghost.webp",
  grass: "/grass.webp",
  ground: "/ground.webp",
  ice: "/ice.webp",
  normal: "/normal.webp",
  poison: "/poison.webp",
  psychic: "/psychic.webp",
  rock: "/rock.webp",
  steel: "/steel.webp",
  water: "/water.webp",
};
